### ISSUE TITLE
东门北侧

### ISSUE THREAD

**Issue by Golevka2001** [Golevka2001/Where-Are-Available-Chargers#3]
# 从北向南

1. ![东门北侧-1](https://user-images.githubusercontent.com/101185502/199643161-b5806548-9f47-40ee-86eb-2e8ede4ae498.jpeg)
2. ![东门北侧-2](https://user-images.githubusercontent.com/101185502/199643228-b9a928f1-9a7d-4aec-8554-0083bc503ce5.jpeg)
3. ![东门北侧-3](https://user-images.githubusercontent.com/101185502/199643165-f8a20379-d507-4df2-82cc-b3b99073526a.jpeg)
4. ![东门北侧-4](https://user-images.githubusercontent.com/101185502/199643168-a95c6697-2597-4b62-bf72-4ec70cc5b6da.jpeg)
5. ![东门北侧-5](https://user-images.githubusercontent.com/101185502/199643177-6b8548e2-aab1-4bdd-b2f4-cf4553ea477e.jpeg)

**Comment by csimide** [comment]
北侧新增（从北向南）

1. （原南门东侧2号桩）
![image](https://user-images.githubusercontent.com/117500413/230724841-5a4ec256-3945-4a41-853d-e3be31ea35f8.png)
2. （原南门东侧1号桩） 
![image](https://user-images.githubusercontent.com/117500413/230724974-642550e4-617f-4578-a433-454d7cce0daa.png)
