### ISSUE TITLE
南门东侧

### ISSUE THREAD

**Issue by Golevka2001** [Golevka2001/Where-Are-Available-Chargers#9]
# 从北向南

1. ![东侧-1](https://user-images.githubusercontent.com/101185502/201675377-aba31296-82dd-45a9-830c-dd3b45c24087.jpeg)
2. ![东侧-2](https://user-images.githubusercontent.com/101185502/201675401-bba37d4c-f4a9-433f-9801-b7887183fe77.jpeg)

**Comment by csimide** [comment]
这两组桩已移到东门北侧，见 #3
